running:
  covariance: default
  score_threshold: 0.01
  max_age_since_update: 2
  min_hits_to_birth: 0
  match_type: bipartite
  asso: giou
  has_velo: true
  nms_thres: 0.1
  motion_model: velo
  asso_thres:
    giou: 1.5
    iou: 0.9
    m_dis: 11

redundancy:
  mode: default
  det_score_threshold: 
    iou: 0.01
    giou: 0.01
    m_dis: 0.1
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5
    m_dis: 11

data_loader:
  nms: true
  nms_thres: 0.1
  pc: false