running:
  covariance: default
  score_threshold: 0.5
  max_age_since_update: 2
  min_hits_to_birth: 3
  match_type: bipartite
  asso: giou
  has_velo: false
  motion_model: kf
  asso_thres:
    iou: 0.9
    giou: 1.5
    m_dis: 5

redundancy:
  mode: mm
  det_score_threshold: 
    iou: 0.1
    giou: 0.1
    m_dis: 0.1
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5
    m_dis: 10

data_loader:
  pc: true
  nms: true
  nms_thres: 0.25