running:
  covariance: default
  score_threshold: 0.5
  max_age_since_update: 2
  min_hits_to_birth: 3
  match_type: greedy
  asso: euler
  has_velo: false
  motion_model: fbkf
  asso_thres:
    iou: 0.9
    giou: 1.5
    m_dis: 5
    euler: 2

redundancy:
  mode: mm
  det_score_threshold: 
    iou: 0.1
    giou: 0.1
    m_dis: 0.1
    euler: 0.1
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5
    m_dis: 5
    euler: 2

data_loader:
  pc: true
  nms: false
  nms_thres: 0.25